import { createRequire as __mjCreateRequire } from "node:module"; const require = __mjCreateRequire(import.meta.url);

// probe/vh19Honesty.test.ts
import * as fs from "node:fs";
import * as path from "node:path";
var passed = 0;
var failures = [];
function ok(label, cond, detail = "") {
  if (cond) {
    passed += 1;
    console.log(`  ok   ${label}`);
  } else {
    failures.push(`${label}${detail ? ` \u2014 ${detail}` : ""}`);
    console.log(`  FAIL ${label} \u2014 ${detail}`);
  }
}
function section(n) {
  console.log(`
== ${n}`);
}
var root = ".".length > 0 ? "." : process.cwd();
var read = (p) => fs.readFileSync(path.join(root, p), "utf8");
var exists = (p) => fs.existsSync(path.join(root, p));
section("0. the project root is real before we assert anything about it");
ok("root resolves to the vouchharbor tree", exists("src/views/Harbor.tsx"), root);
section("1. the overstated banner is dead and stays dead");
var harborView = read("src/views/Harbor.tsx");
ok('no unconditional "no mock" claim survives', !/no mock/i.test(harborView), (harborView.match(/.*no mock.*/i) ?? ["clean"])[0].trim().slice(0, 90));
ok('no sentence pairs "real engine" with an absolute denial of simulation', !/real engine[^.]*no\s+mock/i.test(harborView));
ok("the replacement says receipts record what EXECUTED (checkable, not aspirational)", /receipts record what actually executed/i.test(harborView));
ok("the mode is named on the receipt, not just on screen", /engine mode is printed on them/i.test(harborView));
section("2. the simulated disclosure is WIRED to the mode, not hardcoded visible");
ok("a brain-mode check drives the disclosure", /\/simul\/i\.test\(totals\.brain\)/.test(harborView), (harborView.match(/\/simul\/i\.test\([^)]*\)/) ?? ["none"])[0]);
ok("the disclosure is marked for assistive tech", /role="status"/.test(harborView));
ok("it carries a stable hook a UI test can assert on", /data-vh-brain-mode="simulated"/.test(harborView));
ok("it names what IS real during simulation, so it is not just a warning", /routing, receipts, git and tests are real/i.test(harborView));
ok("it tells the user where to change it", /Harbor Master/.test(harborView));
ok("the label is interpolated from the store, so it cannot go stale vs reality", /\{totals\.brain\}/.test(harborView) && !/state\.brain/.test(harborView));
section("3. the vendored catalog must not ship its prompt bodies to the browser");
var gen = read("src/moe/catalog.gen.ts");
ok("catalog.gen.ts is generated, and says so", /GENERATED by tools\/build-specialist-catalog\.mjs/.test(gen));
ok("the generated file carries the provenance header", /VoltAgent\/awesome-claude-code-subagents/.test(gen) && /MIT/.test(gen));
var bodySample = (() => {
  const dir = path.join(root, "vendor/voltagent-specialists/agents");
  if (!fs.existsSync(dir)) return "";
  const f = fs.readdirSync(dir).filter((x) => x.endsWith(".md"))[0];
  return f ? read(path.join("vendor/voltagent-specialists/agents", f)) : "";
})();
ok("a real prompt body exists on disk", bodySample.length > 200, `${bodySample.length}B`);
var fingerprint = bodySample.split(/\r?\n/).map((l) => l.trim()).filter((l) => l.length > 60)[0] ?? "";
ok("no prompt body sentence leaks into the browser module", fingerprint === "" || !gen.includes(fingerprint.slice(0, 50)), fingerprint.slice(0, 60));
ok("bodies are NOT copied into src/ at all", (() => {
  const moeDir = path.join(root, "src/moe");
  const files = fs.readdirSync(moeDir).filter((f) => f.endsWith(".ts"));
  return !files.some((f) => /\.md$/.test(f)) && !exists("src/moe/agents");
})(), fs.readdirSync(path.join(root, "src/moe")).join(","));
section("4. the gate keeps qualifying its own number");
var gateSrc = read("src/moe/gate.ts");
ok("the agreement-vs-competence caveat is in the source, not added by the UI", /EVIDENCE=USER-AGREEMENT-NOT-INDEPENDENT-COMPETENCE/.test(gateSrc));
ok("it is emitted only for agent-authored grading", /outcome\.startsWith\("escalation-granted"\)/.test(gateSrc) || /agent-authored/.test(gateSrc));
ok("unanswered items are counted, so the caveat can be verified", /unanswered=\$\{unanswered(Count)?\}/.test(gateSrc));
ok("both outcomes route their receipt through ONE builder (no duplicated field list to drift)", (() => {
  const calls = gateSrc.match(/receiptNote:\s*receipt\(/g) ?? [];
  const inlined = gateSrc.match(/receiptNote:\s*`/g) ?? [];
  return calls.length === 2 && inlined.length === 0;
})(), `builder-calls=${(gateSrc.match(/receiptNote:\s*receipt\(/g) ?? []).length} inlined=${(gateSrc.match(/receiptNote:\s*`/g) ?? []).length}`);
ok(
  "the field list is spelled out exactly once in the module",
  (gateSrc.match(/score=\$\{percent\}%/g) ?? []).length === 1,
  `${(gateSrc.match(/score=\$\{percent\}%/g) ?? []).length} occurrences`
);
ok("the caveat is a named constant, so it cannot be half-removed by a later edit", /const AGREEMENT_CAVEAT = " \| EVIDENCE=USER-AGREEMENT/.test(gateSrc));
ok(
  "the caveat is attached only on the granted path, never on a refusal",
  /p\.gradingMode === "agent-authored" \? AGREEMENT_CAVEAT : ""/.test(gateSrc)
);
section("5. the merge is attributed where a person will actually look");
ok("NOTICE names the pinned commit, not a moving branch", /3097abe2d0d1e83a9023c7a8d054c00aace24990/.test(read("vendor/voltagent-specialists/NOTICE")));
ok("NOTICE records what was deliberately NOT merged", /mastra/i.test(read("vendor/voltagent-specialists/NOTICE")) && /openclaw/i.test(read("vendor/voltagent-specialists/NOTICE")));
ok("the optional-Mastra decision is written down as a decision", /optional npm peer|optionalDependencies/.test(read("vendor/voltagent-specialists/NOTICE")));
section("6. counts the docs promise are the counts that exist");
var probeCount = fs.readdirSync(path.join(root, "probe")).filter((f) => /\.test\.tsx?$/.test(f) && !f.startsWith(".")).length;
var readme = read("README.md");
var declared = Number((readme.match(/npm test\s*#\s*(\d+) suites/) ?? [])[1] ?? -1);
ok(`README 'npm test' comment matches the real suite count (${probeCount})`, declared === probeCount, `README says ${declared}, probe/ has ${probeCount}`);
var buildInfo = read("verify/BUILD-INFO.txt");
ok(`BUILD-INFO states the same count (${probeCount})`, new RegExp(`${probeCount} probe suites`).test(buildInfo), buildInfo.match(/\d+ probe suites/)?.[0] ?? "none");
console.log(`
${passed} passed, ${failures.length} failed`);
if (failures.length) {
  for (const f of failures) console.log(`  ! ${f}`);
  process.exit(1);
}
